spring:
  datasource:
      url: jdbc:mysql://localhost:3306/rrrent?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: 32kishjsA
mybatis:
   mapperLocations: classpath:/mapper/*.xml
swagger.enable: true

wx:
  applet:
   appid: zxfgs
   appsecret: sdfg
